### ISSUE TITLE
wow！分享精神，酷！

### ISSUE THREAD

**Issue by Sharkafuc** [xuanhun/PythonHackingBook1#4]
跌跌撞撞写程序5年多了，按部就班学了各种语言，做过网站，玩过可视化，写应用程序，现在工作是做游戏。总是想入门黑客，但每每插肩而过渠道偏而少。看到这repo大纲，支持作者技术传播，给自己立个flag，工作了也会常来关注，也希望作者坚持更新。

**Comment by xuanhun** [comment]
> 跌跌撞撞写程序5年多了，按部就班学了各种语言，做过网站，玩过可视化，写应用程序，现在工作是做游戏。总是想入门黑客，但每每插肩而过渠道偏而少。看到这repo大纲，支持作者技术传播，给自己立个flag，工作了也会常来关注，也希望作者坚持更新。

会的，放心，直到图书出版
