### ISSUE TITLE
求助：VS中python运行pip添加itchat微信模块失败

### ISSUE THREAD

**Issue by ANT-Yang** [xuanhun/PythonHackingBook1#9]
各位学长好，这篇教程看了后，我尝试着安装了itchat的微信模块，但是发现import之后。itchat里的方法和变量不能正常引用（类似出现像：module 'itchat' has no attribute 'auto_login'）的现象。我到阿如的步骤是直接在VS命令行里pip install itchat 了，请问有遇到同样问题的朋友或者大神帮帮忙吗，非常感谢~

**Comment by ANT-Yang** [comment]
我找到问题了(#^.^#)

**Comment by xuanhun** [comment]
> 我找到问题了(#^.^#)

详细阐述下问题，给别人参考
